name: Code Quality Check

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "**.yaml"
      - "**.json"
      - "**.sql"
      - "LICENSE"
      - ".gitignore"
      - ".gitattributes"
      - ".env.example"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "**.yaml"
      - "**.json"
      - "**.sql"
      - "LICENSE"
      - ".gitignore"
      - ".gitattributes"
      - ".env.example"

jobs:
  quality-check:
    name: Node ${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run Code Quality Checks with pnpm
        run: pnpm run check
